<?php


/**
 * Implements hook_form_alter()
 */
function ext_form_form_alter(&$form, &$form_state, $form_id)
{
  // отключить HTML5 валидацию на всех формах
  $form['#attributes']['novalidate'] = '';

  if (strpos($form_id, 'webform_client_form') === 0) {
    $form["actions"]["submit"]["#attributes"]["class"][] = 'btn-brand';
    $form["actions"]["submit"]["#attributes"]["class"][] = 'btn-wide';
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function ext_form_form_webform_client_form_4_alter(&$form, &$form_state)
{
  // заполнить поле текста, если он присутствует в ссылке
  if (isset($_GET['message'])) {
    $form["submitted"]["message"]["#default_value"] = check_plain($_GET['message']);
  }

  // ajax обновление формы отправки заявки
  $form['#prefix'] = '<div id="' . $form["#id"] . '-wrapper">';
  $form['#suffix'] = '</div>';

  $form['actions']['submit']['#ajax'] = [
    'callback' => 'ext_form_webform_client_form_4_ajax_callback',
    'wrapper' => $form["#id"] . '-wrapper',
  ];

  $form["#submit"][] = 'ext_form_rebuild_submit';
}
function ext_form_webform_client_form_4_ajax_callback($form, $form_state)
{
  if (!empty($form["#submission"])) {
    $form['submitted']['complete'] = [
      '#markup' => '<div class="complete">' .
        '<h4>' . t('Message been sent.') . '</h4>' .
        '<p>' . t('I will contact you as soon as possible.') . '</p>' .
        '</div>',
    ];
  }
  // сбросить сообщение после обновления страницы
  unset($_SESSION["webform_confirmation"]);

  return $form;
}

function ext_form_rebuild_submit($form, &$form_state)
{
  $form_state['rebuild'] = TRUE;
}
