<?php


/**
 * Implements hook_form_alter()
 */
function ext_form_form_alter(&$form, &$form_state, $form_id)
{
  // отключить HTML5 валидацию на всех формах
  $form['#attributes']['novalidate'] = '';

  if (strpos($form_id, 'webform_client_form') === 0) {
    $form["actions"]["submit"]["#attributes"]["class"][] = 'btn-brand';
    $form["actions"]["submit"]["#attributes"]["class"][] = 'btn-wide';
  }
}
