<?php

/**
 * Implements hook_menu().
 */
function sec_wishlist_menu()
{
  return [
    'wishlist/add/%' => [
      'page callback' => 'sec_wishlist_add_item',
      'page arguments' => [2],
      'access callback' => 'ext_user_user_account_access',
      'type' => MENU_CALLBACK,
    ],
    'wishlist/delete/%' => [
      'page callback' => 'sec_wishlist_delete_item',
      'page arguments' => [2],
      'access callback' => 'ext_user_user_account_access',
      'type' => MENU_CALLBACK,
    ],
    'user/wishlist' => [
      'title' => 'Wishlist',
      'page callback' => 'sec_wishlist_user_wishlist',
      'access callback' => 'ext_user_user_account_access',
      'type' => MENU_CALLBACK,
    ],
  ];
}

function sec_wishlist_user_wishlist()
{
  drupal_goto('user/' . $GLOBALS['user']->uid . '/wishlist');
}

function sec_wishlist_add_item($entity_id)
{
  // если авторизован
  if ($uid = $GLOBALS['user']->uid) {
    // если ещё не в списке
    if (!sec_wishlist_get_item_wishlist_id($entity_id)) {
      // если сущность существует
      $entity_wr = entity_metadata_wrapper('node', $entity_id);
      if ($entity_wr->getIdentifier()) {
        // добавить запись Избранного
        $item = entity_create('wishlist', [
          'type' => 'wishlist',
          'created' => REQUEST_TIME,
          'uid' => $uid,
        ]);
        entity_save('wishlist', $item);
        $item_wr = entity_metadata_wrapper('wishlist', $item);
        $item_wr->field_wishlist_entity->set($entity_wr->getIdentifier());
        $item_wr->save();
      }
    }

    $like = theme('wishlist_btn', ['in_list' => true, 'entity_id' => $entity_id]);
    $commands[] = ajax_command_replace('#wishlist-' . $entity_id, $like);
    ajax_deliver(['#type' => 'ajax', '#commands' => $commands]);

//    if (!empty($_GET['destination'])) {
//      drupal_goto($_GET['destination']);
//    }
  }
}

function sec_wishlist_delete_item($entity_id)
{
  if ($item_id = sec_wishlist_get_item_wishlist_id($entity_id)) {
    entity_delete('wishlist', $item_id);
  }

  $like = theme('wishlist_btn', ['in_list' => false, 'entity_id' => $entity_id]);
  $commands[] = ajax_command_replace('#wishlist-' . $entity_id, $like);
  ajax_deliver(['#type' => 'ajax', '#commands' => $commands]);

//  drupal_goto($_GET['destination'] ?? $_SERVER['REQUEST_URI']);
}

/**
 * Проверить наличие сущности в списке Пользователя и вернуть ID записи
 */
function sec_wishlist_get_item_wishlist_id($entity_id, $user_id = null)
{
  $user_id = $user_id ?? $GLOBALS['user']->uid;
  $query = db_select('eck_wishlist', 'w');
  $query->condition('w.uid', $user_id);
  $query->innerJoin('field_data_field_wishlist_entity', 'we', 'we.entity_id = w.id');
  $query->condition('we.field_wishlist_entity_target_id', $entity_id);
  $query->addField('w', 'id');

  return $query->execute()->fetchField();
}

/**
 * Вернуть список ID сущностей в списке Пользователя
 */
function sec_wishlist_get_items_in_wishlist($user_id = null)
{
  $user_id = $user_id ?? $GLOBALS['user']->uid;
  $query = db_select('eck_wishlist', 'w');
  $query->condition('w.uid', $user_id);
  $query->addField('w', 'id');

  return $query->execute()->fetchField();
}

/**
 * Implements hook_theme().
 */
function sec_wishlist_theme()
{
  return [
    'wishlist_btn' => array(
      'variables' => ['in_list' => null, 'entity_id' => null],
    ),
  ];
}

function theme_wishlist_btn($vars)
{
  $classes = ['btn', 'btn-brand', 'btn-small', 'btn-uppercase'];
  $classes = array_merge($classes, $GLOBALS['user']->uid ? ['use-ajax'] : []);
  $destination = $_SERVER['REQUEST_URI'];
  if ($vars['in_list']) {
    $path = $GLOBALS['user']->uid ? 'wishlist/delete/' . $vars['entity_id'] : 'need-login';
    $link = l('in list', $path, [
      'html' => true,
      'attributes' => ['title' => t('Remove from Wishlist'), 'class' => $classes],
      'query' => ['destination' => $destination],
    ]);
  } else {
    $path = $GLOBALS['user']->uid ? 'wishlist/add/' . $vars['entity_id'] : 'need-login';
    $link = l('to list', $path, [
      'html' => true,
      'attributes' => ['title' => t('Add to Wishlist'), 'class' => $classes],
      'query' => ['destination' => $destination],
    ]);
  }

  drupal_add_library('system', 'drupal.ajax');
  drupal_add_library('system', 'jquery.form');

  return '<div id="wishlist-'. $vars['entity_id'] . '" class="wishlist-btn">' . $link . '</div>';
}


