<?php

/**
 * Implements hook_block_info().
 */
function ext_block_block_info()
{
  return [
    'custom-block-new-items' => [
      'info' => t('CB | New items'),
    ],
  ];
}

/**
 * Implements hook_block_view().
 */
function ext_block_block_view($delta = '')
{
  $block = [];

  // блоки с динамически формируемым содержимым
  if ($delta == 'custom-block-new-items') {
    if ($novelties = sec_catalog_get_promoted_items()) {
      $cards = [];
      foreach ($novelties as $product) {
        $view = node_view($product, 'teaser');
        $rendered = drupal_render($view);
        $cards[] = $rendered;
      }
      $block['content'] = theme($delta, ['cards' => $cards, 'title' => t('New items')]);
    } else $block['content'] = null;
  }

  // блоки со статичной разметкой
  elseif (strpos($delta, 'custom-block-') === 0) {
    $block['content'] = theme($delta);
  }

  // общее для программных блоков
  if (strpos($delta, 'custom-block-') === 0) {
    $block['subject'] = null;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function ext_block_theme()
{
  return [
    'custom-block-new-items'   => [
      'variables' => [],
      'template' => 'templates/block-new-items',
    ],
  ];
}
