<?php

/**
 * Implements hook_menu().
 */
function sec_about_menu()
{
  $items['about'] = [
    'title' => 'About',
    'page callback' => 'sec_about_page',
    'access arguments' => ['access content'],
    'type' => MENU_NORMAL_ITEM,
  ];

  return $items;
}

/**
 * Implements hook_theme().
 */
function sec_about_theme()
{
  return [
    'about_page' => [
      'variables' => [],
      'template' => 'templates/about-page',
    ]
  ];
}

function sec_about_page()
{
  if (variable_get('path_breadcrumbs_home_link_enabled')) $breadcrumbs[] = l(t('Home'), null);
  $breadcrumbs[] = t('About');
  drupal_set_breadcrumb($breadcrumbs);

  return theme('about_page');
}

function sec_about_preprocess_page(&$vars)
{
  if ($_GET['q'] == 'about') {
    $vars['is_title_on'] = false;
  }
}
